name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Debug Firebase Service Account Key
        run: echo "echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY}}"

      - name: Set up Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --token=${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
