name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Firebase Login
        run: npm install -g firebase-tools
      - run: echo "$FIREBASE_TOKEN" | firebase login --no-localhost

      - name: Deploy to Firebase
        run: firebase deploy --token "$FIREBASE_TOKEN" --project myportfolio-393919
